server:
  port: 8089
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/book_network
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: localhost
    port: 1025
    username: mouad
    password: mouad
    properties:
      mail:
        smtp:
          trust : "*"
        auth : true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application :
  security :
      jwt :
        secretKey : bW91QGRsbTlAd2RiekBmb3V5ZGl6a2ZpaEB6YmlYWxoYWhoaGFoYWg=hWdk1937
        expiration : 8460000
  mailing :
    frontend :
      activation-url : http://localhost:4200/activation-email
  file :
    path:
      photo-path : ./uploads
